// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';
//  // ...
// await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByq0gZHlOvwgR_psKXBRlGheONvp0rfrk',
    appId: '1:1062105611512:web:10453416c20665cfd54f0d',
    messagingSenderId: '1062105611512',
    projectId: 'daely-12fb1',
    authDomain: 'daely-12fb1.firebaseapp.com',
    storageBucket: 'daely-12fb1.appspot.com',
    measurementId: 'G-YX5CHJPEYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3hrn78eDpJzuP_xpPZZvMairAn_DpdaI',
    appId: '1:1062105611512:android:a33a0a4e2887d87ed54f0d',
    messagingSenderId: '1062105611512',
    projectId: 'daely-12fb1',
    storageBucket: 'daely-12fb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGCrbEl1d-KiyqgAX96L_9kmnRGZHCThw',
    appId: '1:1062105611512:ios:a0c7ab514996eaced54f0d',
    messagingSenderId: '1062105611512',
    projectId: 'daely-12fb1',
    storageBucket: 'daely-12fb1.appspot.com',
    iosClientId:
        '1062105611512-huver8idagl6qk2t1h9f3in3ul4ne22n.apps.googleusercontent.com',
    iosBundleId: 'com.example.daelyProto11',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGCrbEl1d-KiyqgAX96L_9kmnRGZHCThw',
    appId: '1:1062105611512:ios:a0c7ab514996eaced54f0d',
    messagingSenderId: '1062105611512',
    projectId: 'daely-12fb1',
    storageBucket: 'daely-12fb1.appspot.com',
    iosClientId:
        '1062105611512-huver8idagl6qk2t1h9f3in3ul4ne22n.apps.googleusercontent.com',
    iosBundleId: 'com.example.daelyProto11',
  );
}
